version: "3.8"

services:
  web_api:
    container_name: web-api
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        APP_PORT: 8888
    network_mode: host
    healthcheck:
      test: curl -f http://localhost:8888/ping || exit 1
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 30s