version: "3.8"

services:
  web_api:
    container_name: web-api
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        APP_PORT: 8888
    network_mode: host
    test: curl -f http://localhost:8888/ping || exit 1
    # ports:
    # - target: 8888
    #   published: 80
    #   mode: bridge
    # test: 